### ISSUE TITLE
Highscore ui 개선

### ISSUE THREAD

**Issue by spaceOfSoul** [eeArcadePlatformer/jumpGame#21]
#### **설명**:

현재 `HighScoreUI` 클래스는 순위별로 이전 사용자의 점수 기록을 표시합니다. 추가 패널과 애니메이션 효과를 요구합니다.

#### **요구 사항**:

1. high score가 그려질 때에 점수 패널 뒤를 채워줄 패널을 요구합니다. 버튼과 같은 갈색-흰색 계열의 사각형이 좋아보입니다. 새로운 이미지파일을 만들어 써도 됩니다.
2. 점수가 시간을 두고 하나씩 나타나야 합니다. 그냥 나타나도 괜찮고, 회전 등의 효과가 있어도 괜찮습니다.

#### **추가**:
`HighScoreUI` 클래스를 사용하는 기존 코드(main.py)는 수정 없이 계속 작동해야 합니다. 수정 후 구동이 되는지 테스트 부탁드립니다.

**Comment by msk9947** [comment]
확인했습니다.
