### ISSUE TITLE
게임 가이드 클래스 추가

### ISSUE THREAD

**Issue by spaceOfSoul** [eeArcadePlatformer/jumpGame#22]
#### **설명**:

본 게임에 진입하기 전, 사용자에게 게임의 사용법을 알려주고 시작합니다.

#### **요구 사항**:

1. 방향키 이동과 스페이스바 점프에 대한 사용법을 이용자에게 알려줍니다.
2. 간략한 텍스트와 이미지를 포함합니다.

#### **추가**:
mian.py의 홈화면에 우선 적용하여 구동여부에 대해 테스트를 진행합니다. commit 및 pr 시 main.py는 원상복구 시키거나 commit에서 제외합니다.

**Comment by 23-PJY** [comment]
확인했습니다
